FROM jruby:9.2.8

ENV RAILS_ENV=production

RUN gem install bundler

WORKDIR /app

# Copy our rails source code into container
COPY . .

#
RUN bundle install

CMD ["rake", "devops:db_setup_for_docker"]