module Unanet
  module Reports
    module Columns
      PERSON_CODE = 'PERSON CODE'
      PERSON_LAST_NAME = 'PERSON LAST NAME'
      PERSON_FIRST_NAME = 'PERSON FIRST NAME'
      PERSON_EMAIL_ID = 'PERSON EMAIL ID'
      PERSON_ACTIVE = 'PERSON ACTIVE'
      PERSON_DEFAULT_PAY_CODE = 'PERSON DEFAULT PAY CODE'
      PERSON_TIME_ENTRY_INCREMENT = 'PERSON TIME ENTRY INCREMENT'
      PERSON_TIME_PERIOD_TYPE = 'PERSON TIME PERIOD TYPE'
      PERSON_TIME_PERIOD_NAME = 'PERSON TIME PERIOD NAME'
      TIMESHEET_CELL_PROJECT_CODE = 'TIMESHEET CELL PROJECT CODE'
      TIMESHEET_CELL_TASK_NAME = 'TIMESHEET CELL TASK NAME'
      TIMESHEET_CELL_PROJECT_TITLE = 'TIMESHEET CELL PROJECT TITLE'
      TIMESHEET_TIME_PERIOD_BEGIN_DATE = 'TIMESHEET TIME PERIOD BEGIN DATE'
      TIMESHEET_TIME_PERIOD_END_DATE = 'TIMESHEET TIME PERIOD END DATE'
      TIMESHEET_CELL_WORK_DATE = 'TIMESHEET CELL WORK DATE'
      TIMESHEET_STATUS = 'TIMESHEET STATUS'
      TIMESHEET_STATUS_DATE = 'TIMESHEET STATUS DATE'
      TIMESHEET_CELL_HOURS = 'TIMESHEET CELL HOURS'
      TIMESHEET_CELL_CLASSIFICATION = 'TIMESHEET CELL CLASSIFICATION'
      TIMESHEET_CELL_LABOR_CATEGORY_NAME = 'TIMESHEET CELL LABOR CATEGORY NAME'
      TIMESHEET_CELL_COMMENTS = 'TIMESHEET CELL COMMENTS'
    end

  end
end