#role strings can be found in './lib/roles/roles'
#contributor role automatically added to all users (no need to specify here)
cristopher.shupp@vetsez.com:
  - 'pm'
  - 'admin'
greg.bowman@vetsez.com:
  - 'pm'
  - 'admin'
albin.santiago@vetsez.com:
  - 'admin'
elisa.hallberg@vetsez.com:
  - 'admin'
maggie.nham@vetsez.com:
  - 'pm'
  - 'senior_pm'
kate.glaeser@vetsez.com:
  - 'pm'
lam.ly@vetsez.com:
  - 'pm'
jeff.udell@vetsez.com:
  - 'pm'
  - 'senior_pm'
ken.price@vetsez.com:
  - 'senior_pm'
nathan.pope@vetsez.com:
  - 'senior_pm'
